[package]
name = "ttyt-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ttyt"
path = "src/main.rs"

[dependencies]
ttyt-core = { workspace = true }
ttyt-ui = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
