[package]
name = "smart-console-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "smart-console"
path = "src/main.rs"

[dependencies]
smart-console-core = { workspace = true }
smart-console-ui = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
