[package]
name = "ttyt-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
directories = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
serialport = { workspace = true }
tracing = { workspace = true }
